packages:
  - apps/*
  - packages/*
  - "!**/flutter"
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  typescript: ^7.0.2
  next-themes: ^0.4.6
  react: ^19.2.6
  react-dom: ^19.2.6
  "@types/react": ^19.2.15
  "@types/react-dom": ^19.2.3
  alchemy: ^0.91.2
minimumReleaseAgeExclude:
  - "@mhaadi/svg@0.1.0"
  - '@astrojs/markdown-satteri@0.3.2'
  - astro@7.0.2
