/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvgRouteImport } from './routes/svg'
import { Route as IndexRouteImport } from './routes/index'

const SvgRoute = SvgRouteImport.update({
  id: '/svg',
  path: '/svg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/svg': typeof SvgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/svg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/svg'
  id: '__root__' | '/' | '/svg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SvgRoute: typeof SvgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/svg': {
      id: '/svg'
      path: '/svg'
      fullPath: '/svg'
      preLoaderRoute: typeof SvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SvgRoute: SvgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
